### ISSUE TITLE
Screenshots and fornix module failed for subject

### ISSUE THREAD

**Issue by enjoy-our-life** [reuter-lab/qatools-python#21]
Hi,
After I ran the qatools for some Freesurfer subjects.In the output folder of qatools.py,screenshots folder is empty and cc.png cannot find.
ERROR：screenshots module failed for subject
ERROR：fornix module failed for subject
Please let me know how to resolve such issue?
Thank you very much.
Yang

**Comment by enjoy-our-life** [comment]
I install scikit-image==0.19.2 not skimage.Will this affect the running of the code?

**Comment by kdiers** [comment]
Hello,

I think this is basically the same, so I would not expect problems.

**Comment by kdiers** [comment]
About the screenshots / fornix module failures: it is a bit hard to tell how to fix it without further information; does it happen for many cases, or just a few ones?

**Comment by enjoy-our-life** [comment]
> Hello,
> 
> I think this is basically the same, so I would not expect problems.



> About the screenshots / fornix module failures: it is a bit hard to tell how to fix it without further information; does it happen for many cases, or just a few ones?

I had tried run 224 cases,all of them are same results.

**Comment by enjoy-our-life** [comment]
> About the screenshots / fornix module failures: it is a bit hard to tell how to fix it without further information; does it happen for many cases, or just a few ones?

what further information do you need .I can provide them

**Comment by enjoy-our-life** [comment]
> About the screenshots / fornix module failures: it is a bit hard to tell how to fix it without further information; does it happen for many cases, or just a few ones?

What further information do you need? I can provide them.

**Comment by kdiers** [comment]
OK, thanks for the information. Maybe could you also let me know which FreeSurfer version you are using?

Apart from that, I can see three potential sources for the error: the data, the environment/dependencies, or the scripts themselves:

The easiest way forward might be if you could send one example case so that I can try to replicate the issue; I could provide an upload link for that purpose. But I see that it may not be possible to share any of the data; in that case we'll need to think of another solution.

About the environment/dependencies: we typically recommend to run the scripts within a virtual environment (e.g. using `virtualenv`) because this gives more control / flexibility about which external libraries are installed. I imagine that this could also help in identifying the problem.

Lastly, there could also be an error within the scripts themselves, but I have to admit that I did not see it with our local test cases so far - so I'd need to think about that more.

**Comment by enjoy-our-life** [comment]
> 好的，谢谢你的信息。也许你也可以让我知道你正在使用哪个FreeSurfer版本？
> 
> 除此之外，我可以看到错误的三个潜在来源：数据，环境/依赖项或脚本本身：
> 
> 最简单的方法可能是，如果您可以发送一个示例案例，以便我可以尝试复制该问题;我可以为此目的提供上传链接。但我看到可能无法共享任何数据;在这种情况下，我们需要考虑另一种解决方案。
> 
> 关于环境/依赖项：我们通常建议在虚拟环境中运行脚本（例如使用），因为这可以更好地控制/灵活地安装哪些外部库。我想这也有助于确定问题。`virtualenv`
> 
> 最后，脚本本身也可能存在错误，但我不得不承认，到目前为止，我还没有在我们的本地测试用例中看到它 - 所以我需要考虑更多。

**Comment by enjoy-our-life** [comment]
> 好的，谢谢你的信息。也许你也可以让我知道你正在使用哪个FreeSurfer版本？
> 
> 除此之外，我可以看到错误的三个潜在来源：数据，环境/依赖项或脚本本身：
> 
> 最简单的方法可能是，如果您可以发送一个示例案例，以便我可以尝试复制该问题;我可以为此目的提供上传链接。但我看到可能无法共享任何数据;在这种情况下，我们需要考虑另一种解决方案。
> 
> 关于环境/依赖项：我们通常建议在虚拟环境中运行脚本（例如使用），因为这可以更好地控制/灵活地安装哪些外部库。我想这也有助于确定问题。`virtualenv`
> 
> 最后，脚本本身也可能存在错误，但我不得不承认，到目前为止，我还没有在我们的本地测试用例中看到它 - 所以我需要考虑更多。

I use the FreeSurfer 7.2. I run qatools in the ubuntu 20.04.3 LTS amd64
This link is the result of freesurfer for one of the patients:
https://drive.google.com/drive/folders/1t_o7lo69JBV6DNJonWkqMCU9LNkAtzd7?usp=sharing
Do you need any other information？

**Comment by kdiers** [comment]
Thanks for the upload; I've deleted the message because the link is no longer needed.

I've run the scripts with that case on a Ubuntu 20.04 installation and using FreeSurfer 7.2. I created a virtual environment using `virtualenv`, downloaded the scripts, used `pip3 install -r requirements.txt` to install the required python packages, plus a separate installation of `scikit-image`. 

With this setup, I could not see any errors, i.e. all output files were present. 

Thanks for reporting your observation, I think it's important and it would be good to know the reason. My best guess is that it's some depencency / environment issue, but at the moment I can't really tell the exact source of the problem. Please let me know if it persists or if you have additional information.

**Comment by enjoy-our-life** [comment]
> scikit-image

Sorry, it is my fault.I do as you said，sudo apt install virtualenv，pip3 install -r requirements.txtscikit-image.
The code can be run successfully.I used to run the code directly on ubuntu.Your guess is right and it's some depencency / environment issue.So I create a new environment to run the code.The qatools has greatly improved my efficiency in checking images.

**Comment by kdiers** [comment]
Thanks for the feedback, that's good to know.
