### ISSUE TITLE
--screenshots-html, --fornix-html not working

### ISSUE THREAD

**Issue by BadCoder98** [reuter-lab/qatools-python#36]
## Question/Support Request
The --screenshots--html and --fornix-html arguments are not working properly for a colleague and I when we try and run them. the error message reads: `qatools.py: error: unrecognized arguments: <-- insert either argument name -->`. The other ones work fine. 
...

## Screenshots
See attachment for details.
...

Error message: `qatools.py: error: unrecognized arguments: <-- insert either argument name -->`.

## Environment
 - qatools-python Version: 3.10
 - OS: WSL2 and CentOS 7
 - CPU: Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz   3.19 GHz

We have attempted using both WSL2 and CentOS 7 via an SSH client on a Windows machine for this, but the error has persisted.

### Execution
![err](https://user-images.githubusercontent.com/128188595/226052107-c657577e-1ed9-4aed-8013-688f7ebd909b.PNG)

**Comment by kdiers** [comment]
Hello, and thanks for the report. I believe that this results from a version issue, i.e. a conflict with the older version of the toolbox that is included with FreeSurfer and also has a `qatools.py` file. However, that `qatools.py` file did not have the `--fornix-html` or `--screenshots-html` options at the time when it was included with FreeSurfer. I assume that the `qatools.py` file is on the search path after FreeSurfer is sourced. To avoid this issue, download the most recent GitHub version of the package, and call the downloaded `qatools.py` either from its directory or specify the path when calling it (e.g.,`<PATH>/qatools.py`). This should work - otherwise please write. And thanks again for reporting, we will address this issue in the upcoming release (and update the README before that).

**Comment by Aminin2023** [comment]
I have downloaded the most recent GitHub version of the package, and called the downloaded qatools.py by specifying the path when calling it (e.g.,<PATH>/qatools.py), still get the same error for --screenshots-html and --fornix-html.

In addition, I only receive one screenshot in PNG format, while in the previous versions there were multiple (slice by slice) screenshots in QA.

**Comment by kdiers** [comment]
Just a quick notice that we have released version 2.0 of this toolbox, which should solve these issues. If anything persists, please feel free to reopen this issue or write otherwise.
