### ISSUE TITLE
WM snr discrepancy between qatools and mri_segstats --qa-stats

### ISSUE THREAD

**Issue by WilliamFCB** [reuter-lab/qatools-python#38]
Hi 
I ran qa-tools and mri_segstats --qa-stats on a dataset and noticed that the norm wm snr reported by mri_segstats was higher than reported by qa_tools (respectively ~ 19.017 and 28.09)

Out of curiosity, is this because mri_segstats excludes the top and bottom 2% before calculating the WM stats?

thanks
William

**Comment by kdiers** [comment]
Hi, and apologies for the very late reply. To be honest, I can only speculate about these differences. It is possible that the robust calculation in mri_segstats contributes to this difference. On the other hand, I don't know how the computation in mri_segstats is done exactly - and since ours is a free reimplementation, I would not expect perfect agreement a priori. One strategy for further investigation might be to look at the correlation of the metrics from the two packages in a larger sample.

Best regards, Kersten
