### ISSUE TITLE
Add option to set a temporary working directory

### ISSUE THREAD

**Issue by costantinoai** [reuter-lab/qatools-python#56]
## Feature Description
Add the option to set a --workdir flag to set a work directory to save intermediate results (see fMRIprep)
...

## Motivation
Running fsqc on an entire dataset is quite time consuming. If, by any chance, the user gets an error at some point in the pipeline, they are forced to re-start the entire process and the tool is not able to find the already computed intermediate results and re-start from there. This is a major drawback.
...

## Alternatives
If a working directory is set, and all the intermediate results are stored (e.g., see other BIDS tools like fMRIprep), then these intermediate results can be used to re-start a run from where it was left.

**Comment by kdiers** [comment]
Thanks for your comments and suggestions, this is very helpful. We will discuss what can be implemented, and will give an update about any changes that can be expected the near future.

**Comment by costantinoai** [comment]
No worries! Thank you for the nice tool. I gave these suggestions from a "user" perspective to help development, but no pressure of course :)

**Comment by kdiers** [comment]
Some thoughts about the need / utility of introducing a temporary working directory:
- I agree that it would be useful not having to recompute everything again in case the process exited prematurely. 
- We have tried to avoid such situations by having `try` / `except` clauses around individual processing commands, so that the program will try to continue even if individual cases fail (or exit deliberately, if the `--exit-on-error` flag is set). However, it may well be that this does not help in all situations (for example, if no disk space is remaining, or a power failure, or ...). 
- Therefore, it makes sense to be able to re-start processing for any remaining cases that are not processed yet. One option might be to just use a dedicated `--subjects-file` with the list of remaining cases.  Alternatively, I am thinking of introducing a `--skip-existing` flag: if set, the program will not recompute / overwrite existing results, but proceed with the next case. This leaves it to the user if they rather want to overwrite / recompute (possibly with different settings) or skip already existing cases.
- Maybe I am missing something, but based on these considerations I do not see a strong need / utility of having a temporary working directory. If anything else needs to be taken into account, please comment. Regardless of this, an option to run the program in group-level mode (i.e., creating group-level output from all available cases, as suggested in #58) makes sense, especially if we do individual processing in an incremental way.

**Comment by kdiers** [comment]
A `--skip-existing` processing option has been implemented now and has undergone initial testing. It is part of the development version currently (`dev` branch), which may still change, and will be part of the next release of the software after further testing; likely in July. Closing this issue now, feel free to reopen in case of any issues.
