### ISSUE TITLE
Value: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

### ISSUE THREAD

**Issue by matthewlyyy01** [reuter-lab/qatools-python#63]
I am a beginner of learning MRI analysis. I converted .dcm files to a .nii file. The name of nii file is 01.nii.gz. After I run the Command: **/home/matthew/miniconda3/bin/run_fsqc --subjects_dir ADNI/data/test/subjects/01 --output_dir ADNI/data/test/analysis --subjects-file ADNI/data/test/subjects/01/01.nii.gz**, the error happens. Here is logging.

[INFO: fsqcMain.py:  820]: Found subjects directory ADNI/data/test/subjects/01
[ERROR: fsqcMain.py: 3437]: Error Information:
[ERROR: fsqcMain.py: 3438]: Type: <class 'UnicodeDecodeError'>
[ERROR: fsqcMain.py: 3439]: Value: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

I cannot find the requirements of folder structure, file format and filename format in the documents. Is there anything I misunderstood?

**Comment by kdiers** [comment]
Hello, thanks for your message. One source of confusion may be that this software only works on FastSurfer- or FreeSurfer-processed data. That is, the outputs of these software packages will be checked, and the software cannot be used for single images only. Also, the `--subjects-file` argument is intended for processing a large number of files, and it should be just a text file with subject IDs as generated by the FastSurfer of FreeSurfer analysis. Hope this helps, otherwise please write again.
